import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <div className='bg-gray-400 mx-auto'>
        <header className='bg-primary-3 container mx-auto flex flex-row flex-wrap gap-x-2 items-center px-5 py-5'>
          <h1 className="font-bold text-2xl flex-auto">
              <a href="/" className="flex flex-row flex-wrap gap-x-2 items-center text-accent">
                  <img src="/assets/img/ehya_logo.svg" alt="Shoplive" />
                  <span className='hidden'>Ehya</span>
              </a>
          </h1>
          <div>
            <a href="/" className="flex flex-row flex-wrap gap-x-2 items-center text-accent">
              <img src="/assets/img/ehya_burger_menu.svg" alt="Shoplive - Menu" />
            </a>
          </div>
        </header>
        <main className=''>
          {/* hero section */}
          <section className='container mx-auto flex flex-col flex-wrap gap-x-2 items-center bg-primary-3 py-5'>
            <div className='flex-auto flex flex-col flex-wrap items-center justify-items-center content-center'>
              <p className='text-center'>Samsungs</p>
              <h2 className='text-2xl text-primary-text text-center'>Get Special Watch with Special Prices</h2>
              <ul className='text-muted text-center m-6 hero-list text-base secondary-text'>
                <li className='py-3.5'>Newest OS Support</li>
                <li className='py-3.5'>Water and Dust Resistant</li>
                <li className='py-3.5'>Long lasting battery life</li>
                <li className='py-3.5'>Get a 20% Cashback right now</li>
              </ul>
              <div className='flex-auto flex flex-col flex-wrap items-center justify-items-center content-center px-2.5 py-2.5 bg-white rounded-lg'>
                <input type="text" className='w-full px-2.5 py-3.5' placeholder='Insert your email' autoComplete='no'/>
                <button className='bg-secondary py-3.5 w-full rounded-lg text-white mt-2'>Join Pre-Order</button>
              </div>
            </div>
            
            <div className='relative flex-auto flex flex-col flex-wrap items-center justify-items-center content-center py-8'>
              <img src="/assets/img/circle.svg" alt="Shoplive - Circle" className='absolute top-10 -left-5' />
              <div className='bg-red-100 h-80 w-60 flex-auto flex flex-col flex-wrap items-center justify-items-center content-center'>
                Image Carousel
              </div>
              <img src="/assets/img/pattern.svg" alt="Shoplive - Pattern" className='absolute bottom-16 -left-5' />
              <img src="/assets/img/square.svg" alt="Shoplive - Square" className='absolute bottom-8 -right-5' />
            </div>
          </section>
          <div className='product-carousel bg-primary-3 relative container flex flex-row mx-auto overflow-x-auto'>
            <div className='flex-auto py-2'>
              <div className='w-auto h-24 bg-green-400 flex flex-row gap-4 items-start px-4 py-3'>
                <div className='w-72 bg-white rounded-lg'>1</div>
                <div className='w-72 bg-white rounded-lg'>2</div>
                <div className='w-72 bg-white rounded-lg'>3</div>
                <div className='w-72 bg-white rounded-lg'>4</div>
                <div className='w-72 bg-white rounded-lg'>5</div>
              </div>
            </div>
          </div>
        </main>
        <footer className='bg-white container mx-auto flex flex-col flex-wrap gap-x-2 items-center justify-items-center content-center px-5 py-5'>
          <div className='flex flex-col flex-wrap gap-x-2 items-center justify-items-center content-center'>
            <h2 className="font-bold text-2xl flex-auto items-center flex flex-col justify-items-center content-center">
                <a href="/" className="flex flex-row flex-wrap gap-x-2 items-center text-accent">
                    <img src="/assets/img/footer_logo.svg" alt="Shoplive" />
                    <span className='hidden'>ShopLive</span>
                </a>
            </h2>
            <p className='text-center text-sm text-muted py-6'>Build a modern and creative website with Moonheads Digital</p>
            <section></section>
          </div>
          <div className='grid grid-cols-2 gap-8 text-primary-text text-left'>
            <div>
              <h3 className='text-base'>Product</h3>
              <ul className='text-sm'>
                <li><a href='#'>Landing Page</a></li>
                <li><a href='#'>Features</a></li>
                <li><a href='#'>Documentation</a></li>
                <li><a href='#'>Referral Program</a></li>
                <li><a href='#'>Pricing</a></li>
              </ul>
            </div>
            <div>
              <h3>Services</h3>
              <ul className='text-sm'>
                <li><a href='#'>Documentation</a></li>
                <li><a href='#'>Design</a></li>
                <li><a href='#'>Themes</a></li>
                <li><a href='#'>Illustrations</a></li>
                <li><a href='#'>UI Kit</a></li>
              </ul>
            </div>
            <div>
              <h3>Company</h3>
              <ul className='text-sm'>
                <li><a href='#'>About</a></li>
                <li><a href='#'>Terms</a></li>
                <li><a href='#'>Privacy Policy</a></li>
                <li><a href='#'>Careers</a></li>
              </ul>
            </div>
            <div>
              <h3>More</h3>
              <ul className='text-sm'>
                <li><a href='#'>Documentation</a></li>
                <li><a href='#'>License</a></li>
                <li><a href='#'>Change Log</a></li>
              </ul>
            </div>
          </div>
        </footer>
      </div>
      
    </div>
  )
}

// export async function getStaticProps() {
//   const products = await getAllProducts()

//   return {
//     props: { products }, // will be passed to the page component as props
//   }
// }