import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

import Header from '../components/Header'
import Footer from '../components/Footer'
import Main from '../components/Main'

export default function Home() {
  return (
    <div>
      <Head>
        <title>ShopLive - Your one stop online live shopping</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <div className='bg-gray-400 mx-auto'>
        <Header/>
        <Main/>
        <Footer/>
      </div>
      
    </div>
  )
}

// export async function getStaticProps() {
//   const products = await getAllProducts()

//   return {
//     props: { products }, // will be passed to the page component as props
//   }
// }