import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div>
      <Head>
        <title>ShopLive - Your one stop online live shopping</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <div className='bg-gray-400 mx-auto'>
        <header className='bg-primary-3 container mx-auto flex flex-row flex-wrap gap-x-2 items-center px-5 py-5'>
          <h1 className="font-bold text-2xl flex-auto">
              <a href="/" className="flex flex-row flex-wrap gap-x-2 items-center text-accent">
                  <img src="/assets/img/ehya_logo.svg" alt="Shoplive" />
                  <span className='hidden'>Ehya</span>
              </a>
          </h1>
          <div>
            <a href="/" className="flex flex-row flex-wrap gap-x-2 items-center text-accent">
              <img src="/assets/img/ehya_burger_menu.svg" alt="Shoplive - Menu" />
            </a>
          </div>
        </header>
        <main className=''>
          {/* hero section */}
          <section className='container mx-auto flex flex-col flex-wrap gap-x-2 items-center bg-primary-3 py-5'>
            <div className='flex-auto flex flex-col flex-wrap items-center justify-items-center content-center'>
              <p className='text-center'>Samsungs</p>
              <h2 className='text-2xl text-primary-text text-center'>Get Special Watch with Special Prices</h2>
              <ul className='text-muted text-center m-6 hero-list text-base secondary-text'>
                <li className='py-3.5'>Newest OS Support</li>
                <li className='py-3.5'>Water and Dust Resistant</li>
                <li className='py-3.5'>Long lasting battery life</li>
                <li className='py-3.5'>Get a 20% Cashback right now</li>
              </ul>
              <div className='flex-auto flex flex-col flex-wrap items-center justify-items-center content-center px-2.5 py-2.5 bg-white rounded-lg'>
                <input type="text" className='w-full px-2.5 py-3.5' placeholder='Insert your email' autoComplete='no'/>
                <button className='bg-secondary py-3.5 w-full rounded-lg text-white mt-2'>Join Pre-Order</button>
              </div>
            </div>
            
            <div className='relative flex-auto flex flex-col flex-wrap items-center justify-items-center content-center py-8'>
              <img src="/assets/img/circle.svg" alt="Shoplive - Circle" className='absolute top-10 -left-5' />
              <div className='bg-red-100 h-80 w-60 flex-auto flex flex-col flex-wrap items-center justify-items-center content-center'>
                Image Carousel
              </div>
              <img src="/assets/img/pattern.svg" alt="Shoplive - Pattern" className='absolute bottom-16 -left-5' />
              <img src="/assets/img/square.svg" alt="Shoplive - Square" className='absolute bottom-8 -right-5' />
            </div>
          </section>

          {/* product carousel */}
          <div className='product-carousel bg-primary-3 relative container flex flex-row mx-auto overflow-x-auto'>
            <div className='flex-auto py-2'>
              <div className='w-auto flex flex-row gap-4 items-start px-4 py-3'>
                <div className='w-72 flex flex-col'>
                  <div className='flex flex-row bg-white rounded-lg px-4 py-4'>
                    <div className='w-20 h-20 rounded-lg bg-red-400'></div>
                    <div className='flex flex-col flex-auto mx-4'>
                      <p className='text-sm text-primary-text font-semibold'>Samsung Galaxy Watch 3. Black Metalic Newest</p>
                      <span className='text-sm text-primary-text mt-4 font-semibold'>$1,750.00</span>
                    </div>
                  </div>
                  <span className='h-1 my-1 bg-white rounded-2xl flex flex-col'>
                    <span className='flex-auto bg-primary-2 rounded-2xl' style={{ width: '80%'}}></span>
                  </span>
                </div>
                <div className='w-72 flex flex-col'>
                  <div className='flex flex-row bg-white rounded-lg px-4 py-4'>
                    <div className='w-20 h-20 rounded-lg bg-red-400'></div>
                    <div className='flex flex-col flex-auto mx-4'>
                      <p className='text-sm text-primary-text font-semibold'>Samsung Galaxy Watch 3. Black Metalic Newest</p>
                      <span className='text-sm text-primary-text mt-4 font-semibold'>$1,750.00</span>
                    </div>
                  </div>
                  <span className='h-1 my-1 bg-white rounded-2xl flex flex-col'>
                    <span className='flex-auto bg-primary-2 rounded-2xl' style={{ width: '0%'}}></span>
                  </span>
                </div>
                <div className='w-72 flex flex-col'>
                  <div className='flex flex-row bg-white rounded-lg px-4 py-4'>
                    <div className='w-20 h-20 rounded-lg bg-red-400'></div>
                    <div className='flex flex-col flex-auto mx-4'>
                      <p className='text-sm text-primary-text font-semibold'>Samsung Galaxy Watch 3. Black Metalic Newest</p>
                      <span className='text-sm text-primary-text mt-4 font-semibold'>$1,750.00</span>
                    </div>
                  </div>
                  <span className='h-1 my-1 bg-white rounded-2xl flex flex-col'>
                    <span className='flex-auto bg-primary-2 rounded-2xl' style={{ width: '0%'}}></span>
                  </span>
                </div>
                <div className='w-72 flex flex-col'>
                  <div className='flex flex-row bg-white rounded-lg px-4 py-4'>
                    <div className='w-20 h-20 rounded-lg bg-red-400'></div>
                    <div className='flex flex-col flex-auto mx-4'>
                      <p className='text-sm text-primary-text font-semibold'>Samsung Galaxy Watch 3. Black Metalic Newest</p>
                      <span className='text-sm text-primary-text mt-4 font-semibold'>$1,750.00</span>
                    </div>
                  </div>
                  <span className='h-1 my-1 bg-white rounded-2xl flex flex-col'>
                    <span className='flex-auto bg-primary-2 rounded-2xl' style={{ width: '0%'}}></span>
                  </span>
                </div>
                <div className='w-72 flex flex-col'>
                  <div className='flex flex-row bg-white rounded-lg px-4 py-4'>
                    <div className='w-20 h-20 rounded-lg bg-red-400'></div>
                    <div className='flex flex-col flex-auto mx-4'>
                      <p className='text-sm text-primary-text font-semibold'>Samsung Galaxy Watch 3. Black Metalic Newest</p>
                      <span className='text-sm text-primary-text mt-4 font-semibold'>$1,750.00</span>
                    </div>
                  </div>
                  <span className='h-1 my-1 bg-white rounded-2xl flex flex-col'>
                    <span className='flex-auto bg-primary-2 rounded-2xl' style={{ width: '0%'}}></span>
                  </span>
                </div>
              </div>
            </div>
          </div>

          {/* product recommendation */}
          <section className='container mx-auto flex flex-col flex-wrap bg-white px-5 py-16'>
            <div className='flex flex-col text-center'>
              <h2 className='text-3xl font-semibold text-primary-text'>
                Product Recommendation
                <p className='text-base font-normal py-6 text-secondary-text'>You can choose what our recommendation product here</p>
              </h2>
            </div>
            <div className='flex flex-col gap-5'>
              {/* item wrapper */}
              <div className='group'>
                <div className='flex flex-col flex-wrap px-5 py-5 cursor-pointer rounded-xl group-hover:bg-highlight'>
                <div className='grid justify-items-end'>
                  <div className='w-9 h-9 bg-accent-3 rounded-full flex items-center justify-items-center content-center justify-center'>
                    <a href='/'>
                      <svg xmlns="http://www.w3.org/2000/svg" width="13.6" height="12" viewBox="0 0 13.6 12">
                        <path id="Path" d="M7.118,1.112a3.8,3.8,0,0,1,5.37,5.368l-5.4,5.4a.4.4,0,0,1-.566,0l-5.4-5.4a3.8,3.8,0,0,1,5.37-5.368l.318.318Z" fill="#5a7184"/>
                      </svg>
                    </a>
                  </div>
                </div>
                <div className='grid justify-items-center mb-11'>
                  <div className='w-28 h-28 rounded-lg bg-red-400'></div>
                </div>
                <div className='flex flex-col items-center'>
                  <h4 className='text-center text-lg font-semibold text-primary-text'>Moderna Juice & Vege Blender Silver</h4>
                  <div className='flex flex-row items-start py-5 gap-4'>
                    <p className='text-base text-primary-text'>$1,500.00</p>
                    <p className='text-base line-through text-muted'>$2,000.00</p>
                  </div>
                </div>
                <div className='flex flex-col px-5'>
                    <button className='flex flex-auto rounded-md justify-items-center py-4 group-hover:bg-secondary'>
                      <span className='mx-auto text-secondary group-hover:text-white'>Buy Now</span>
                    </button>
                </div>
                </div>
              </div>

              <div className='group'>
                <div className='flex flex-col flex-wrap px-5 py-5 cursor-pointer rounded-xl group-hover:bg-highlight'>
                <div className='grid justify-items-end'>
                  <div className='w-9 h-9 bg-accent-3 rounded-full flex items-center justify-items-center content-center justify-center'>
                    <a href='/'>
                      <svg xmlns="http://www.w3.org/2000/svg" width="13.6" height="12" viewBox="0 0 13.6 12">
                        <path id="Path" d="M7.118,1.112a3.8,3.8,0,0,1,5.37,5.368l-5.4,5.4a.4.4,0,0,1-.566,0l-5.4-5.4a3.8,3.8,0,0,1,5.37-5.368l.318.318Z" fill="#5a7184"/>
                      </svg>
                    </a>
                  </div>
                </div>
                <div className='grid justify-items-center mb-11'>
                  <div className='w-28 h-28 rounded-lg bg-red-400'></div>
                </div>
                <div className='flex flex-col items-center'>
                  <h4 className='text-center text-lg font-semibold text-primary-text'>Moderna Juice & Vege Blender Silver</h4>
                  <div className='flex flex-row items-start py-5 gap-4'>
                    <p className='text-base text-primary-text'>$1,500.00</p>
                    <p className='text-base line-through text-muted'>$2,000.00</p>
                  </div>
                </div>
                <div className='flex flex-col px-5'>
                    <button className='flex flex-auto rounded-md justify-items-center py-4 group-hover:bg-secondary'>
                      <span className='mx-auto text-secondary group-hover:text-white'>Buy Now</span>
                    </button>
                </div>
                </div>
              </div>

              <div className='group'>
                <div className='flex flex-col flex-wrap px-5 py-5 cursor-pointer rounded-xl group-hover:bg-highlight'>
                  <div className='grid justify-items-end'>
                    <div className='w-9 h-9 bg-accent-3 rounded-full flex items-center justify-items-center content-center justify-center'>
                      <a href='/'>
                        <svg xmlns="http://www.w3.org/2000/svg" width="13.6" height="12" viewBox="0 0 13.6 12">
                          <path id="Path" d="M7.118,1.112a3.8,3.8,0,0,1,5.37,5.368l-5.4,5.4a.4.4,0,0,1-.566,0l-5.4-5.4a3.8,3.8,0,0,1,5.37-5.368l.318.318Z" fill="#5a7184"/>
                        </svg>
                      </a>
                    </div>
                  </div>
                  <div className='grid justify-items-center mb-11'>
                    <div className='w-28 h-28 rounded-lg bg-red-400'></div>
                  </div>
                  <div className='flex flex-col items-center'>
                    <h4 className='text-center text-lg font-semibold text-primary-text'>Moderna Juice & Vege Blender Silver</h4>
                    <div className='flex flex-row items-start py-5 gap-4'>
                      <p className='text-base text-primary-text'>$1,500.00</p>
                      <p className='text-base line-through text-muted'>$2,000.00</p>
                    </div>
                  </div>
                  <div className='flex flex-col px-5'>
                      <button className='flex flex-auto rounded-md justify-items-center py-4 group-hover:bg-secondary'>
                        <span className='mx-auto text-secondary group-hover:text-white'>Buy Now</span>
                      </button>
                  </div>
                </div>
              </div>

              <div className='group'>
                <div className='flex flex-col flex-wrap px-5 py-5 cursor-pointer rounded-xl bg-special'>
                  <h4 className='my-4 text-center text-xl text-white'>Apple Watch 4 2020</h4>
                  {/* count down timer */}
                  <div className="flex flex-row justify-center">
                    <div className='relative flex flex-col justify-center px-2 py-1 rounded-md overflow-hidden'>
                      <span className='text-sm text-white'>10</span>
                      <span className='absolute top-0 left-0 w-32 h-32 bg-white opacity-10'>&nbsp;</span>
                    </div>
                    <div>
                      <span className='flex flex-col justify-center px-2 py-1 text-white'>:</span>
                    </div>
                    <div className='relative flex flex-col justify-center px-2 py-1 rounded-md overflow-hidden'>
                      <span className='text-sm text-white'>25</span>
                      <span className='absolute top-0 left-0 w-32 h-32 bg-white opacity-10'>&nbsp;</span>
                    </div>
                    <div>
                      <span className='flex flex-col justify-center px-2 py-1 text-white'>:</span>
                    </div>
                    <div className='relative flex flex-col justify-center px-2 py-1 rounded-md overflow-hidden'>
                      <span className='text-sm text-white'>54</span>
                      <span className='absolute top-0 left-0 w-32 h-32 bg-white opacity-10'>&nbsp;</span>
                    </div>
                  </div>
                  <div className='grid justify-items-center my-11'>
                    <div className='w-32 h-32 rounded-lg bg-white'></div>
                  </div>
                  <div className='flex flex-col px-5'>
                      <button className='flex flex-auto rounded-md justify-items-center py-4 bg-white group-hover:bg-special'>
                        <span className='mx-auto font-semibold text-special group-hover:text-white'>Buy Now $1,500.00</span>
                      </button>
                  </div>
                </div>
              </div>
            </div>
          </section>

          {/* Hot Item */}
          <section className='relative container mx-auto flex flex-col flex-wrap px-3 py-9 bg-secondary-2'>
            <div className='z-10'>
              <h3 className='text-center text-3xl'>🔥 Hot Item</h3>
              <div className='flex flex-col my-9 bg-white rounded-lg'>
                {/* item wrapper */}
                <div className='group cursor-pointer pt-10'>
                  <div className='flex flex-col mx-2 pb-8 border-b-2'>
                    <div className='grid justify-items-center'>
                      <div className='w-32 h-32 rounded-lg bg-red-500'></div>
                    </div>
                    <h4 className='pt-6 text-center text-lg text-primary-text'>Asus Zenbook Pro 13"</h4>
                    <p className='pt-3 text-center text-sm text-muted'>The specification here</p>
                    <p className='pt-5 text-center text-xl text-secondary font-semibold'>$1,500.00</p>
                  </div>
                </div>

                <div className='group cursor-pointer pt-10'>
                  <div className='flex flex-col mx-2 pb-8 border-b-2'>
                    <div className='grid justify-items-center'>
                      <div className='w-32 h-32 rounded-lg bg-red-500'></div>
                    </div>
                    <h4 className='pt-6 text-center text-lg text-primary-text'>Asus Zenbook Pro 13"</h4>
                    <p className='pt-3 text-center text-sm text-muted'>The specification here</p>
                    <p className='pt-5 text-center text-xl text-secondary font-semibold'>$1,500.00</p>
                  </div>
                </div>

                <div className='group cursor-pointer pt-10'>
                  <div className='flex flex-col mx-2 pb-8 border-b-2'>
                    <div className='grid justify-items-center'>
                      <div className='w-32 h-32 rounded-lg bg-red-500'></div>
                    </div>
                    <h4 className='pt-6 text-center text-lg text-primary-text'>Asus Zenbook Pro 13"</h4>
                    <p className='pt-3 text-center text-sm text-muted'>The specification here</p>
                    <p className='pt-5 text-center text-xl text-secondary font-semibold'>$1,500.00</p>
                  </div>
                </div>

                <div className='group cursor-pointer pt-10'>
                  <div className='flex flex-col mx-2 pb-8'>
                    <div className='grid justify-items-center'>
                      <div className='w-32 h-32 rounded-lg bg-red-500'></div>
                    </div>
                    <h4 className='pt-6 text-center text-lg text-primary-text'>Asus Zenbook Pro 13"</h4>
                    <p className='pt-3 text-center text-sm text-muted'>The specification here</p>
                    <p className='pt-5 text-center text-xl text-secondary font-semibold'>$1,500.00</p>
                  </div>
                </div>

                <div className='grid justify-items-center pt-5 pb-16'>
                  <svg xmlns="http://www.w3.org/2000/svg" width="7.246" height="11.941" viewBox="0 0 7.246 11.941">
                    <path id="chevron-right" d="M1.74,11.748,7.054,6.434a.656.656,0,0,0,0-.928L1.74.192a.656.656,0,0,0-.928,0l-.62.62a.656.656,0,0,0,0,.927L4.4,5.97.191,10.2a.656.656,0,0,0,0,.927l.62.62A.656.656,0,0,0,1.74,11.748Z" fill="#183b56"/>
                  </svg>
                </div>
              </div>

              <div className='flex flex-col mx-2 border-b-2'>
                <button className='py-5 mb-9 rounded-lg bg-secondary text-base text-white font-semibold'>See All Products</button>
              </div>
            </div>

            <div className='absolute top-0 left-0 w-full'>
              <div className="flex items-stretch bg-secondary opacity-10">
                <div className="py-40">&nbsp;</div>
              </div>
            </div>


          </section>
          
          {/* Categories */}
          <section className='container mx-auto flex flex-col pt-8 pb-14 bg-white'>
            <div className="grid grid-cols-2 gap-5 mx-5">
              <div className='group cursor-pointer'>
                <div className='grid justify-items-center px-5 py-5 rounded-lg border-2 group-hover:border-none hover:drop-shadow-2xl group-hover:bg-white'>
                  <svg id="iconspace_Tshirt_B" data-name="iconspace_Tshirt B" xmlns="http://www.w3.org/2000/svg" width="64" height="64" viewBox="0 0 64 64">
                    <circle id="Shape" cx="32" cy="32" r="32" fill="none"/>
                    <path id="Shape-2" data-name="Shape" d="M8,38a2,2,0,0,0,2,2H30a2,2,0,0,0,2-2V16h6a2,2,0,0,0,2-2V6a6,6,0,0,0-6-6H26A6,6,0,0,1,14,0H6A6,6,0,0,0,0,6v8a2,2,0,0,0,2,2H8Z" transform="translate(12 12)" fill="#fff"/>
                    <rect id="Shape-3" data-name="Shape" width="8" height="4" transform="translate(12 24)" fill="#36b37e"/>
                    <rect id="Shape-4" data-name="Shape" width="8" height="4" transform="translate(44 24)" fill="#36b37e"/>
                    <rect id="Shape-5" data-name="Shape" width="24" height="4" transform="translate(20 48)" fill="#36b37e"/>
                    <path id="Shape-6" data-name="Shape" d="M0,0H7A0,0,0,0,1,7,0V2.5A3.5,3.5,0,0,1,3.5,6h0A3.5,3.5,0,0,1,0,2.5V0A0,0,0,0,1,0,0Z" transform="translate(33 23)" fill="#ffc200"/>
                    <path id="Shape-7" data-name="Shape" d="M24,1V27a1,1,0,0,1-1,1H3a1,1,0,0,1-1-1V1A1,1,0,0,0,0,1V27a3,3,0,0,0,3,3H23a3,3,0,0,0,3-3V1a1,1,0,0,0-2,0Z" transform="translate(19 23)" fill="#183b56"/>
                    <path id="Shape-8" data-name="Shape" d="M11,42a3,3,0,0,1-3-3V18H3a3,3,0,0,1-3-3V7A7,7,0,0,1,7,0h8a1,1,0,0,1,1,1A5,5,0,1,0,26,1a1,1,0,0,1,1-1h8a7,7,0,0,1,7,7v8a3,3,0,0,1-3,3H34V39a3,3,0,0,1-3,3Z" transform="translate(11 11)" fill="#183b56"/>
                  </svg>
                  <h3 className='pt-5 text-base text-primary-text font-semibold'>Fashion</h3>
                </div>
              </div>

              <div className='group cursor-pointer'>
                <div className='grid justify-items-center px-5 py-5 rounded-lg border-2 group-hover:border-none hover:drop-shadow-2xl group-hover:bg-white'>
                    <svg id="iconspace_android_phone" data-name="iconspace_android phone" xmlns="http://www.w3.org/2000/svg" width="64" height="64" viewBox="0 0 64 64">
                      <circle id="Shape" cx="32" cy="32" r="32" fill="none"/>
                      <path id="Shape-2" data-name="Shape" d="M24,2V38a2,2,0,0,1-2,2H2a2,2,0,0,1-2-2V2A2,2,0,0,1,2,0H22A2,2,0,0,1,24,2Z" transform="translate(20 12)" fill="#fff"/>
                      <path id="Shape-3" data-name="Shape" d="M3,42a3,3,0,0,1-3-3V3A3,3,0,0,1,3,0H23a3,3,0,0,1,3,3V39a3,3,0,0,1-3,3Z" transform="translate(19 11)" fill="#183b56"/>
                      <path id="Shape-4" data-name="Shape" d="M1,2H5A1,1,0,0,0,5,0H1A1,1,0,0,0,1,2Z" transform="translate(29 47)" fill="#ffc200"/>
                      <path id="Shape-5" data-name="Shape" d="M1,0H17a1,1,0,0,1,1,1V29a1,1,0,0,1-1,1H1a1,1,0,0,1-1-1V1A1,1,0,0,1,1,0Z" transform="translate(23 15)" fill="#36b37e"/>
                    </svg>
                    <h3 className='pt-5 text-base text-primary-text font-semibold'>Handphone</h3>
                </div>
              </div>
              
              <div className='group cursor-pointer'>
                <div className='grid justify-items-center px-5 py-5 rounded-lg border-2 group-hover:border-none hover:drop-shadow-2xl group-hover:bg-white'>
                    <svg id="iconspace_Notebook" xmlns="http://www.w3.org/2000/svg" width="64" height="64" viewBox="0 0 64 64">
                      <circle id="Shape" cx="32" cy="32" r="32" fill="none"/>
                      <path id="Shape-2" data-name="Shape" d="M3,0H33a3,3,0,0,1,3,3V24a1,1,0,0,1-1,1H1a1,1,0,0,1-1-1V3A3,3,0,0,1,3,0Z" transform="translate(14 13)" fill="#183b56"/>
                      <path id="Shape-3" data-name="Shape" d="M32,21V1a1,1,0,0,0-1-1H1A1,1,0,0,0,0,1V21Z" transform="translate(16 15)" fill="#36b37e"/>
                      <rect id="Shape-4" data-name="Shape" width="28" height="17" rx="1" transform="translate(18 17)" fill="#fff"/>
                      <path id="Shape-5" data-name="Shape" d="M2.69,0H38.281l2.614,11.325A3,3,0,0,1,37.972,15H3A3,3,0,0,1,.077,11.325Z" transform="translate(11.514 36)" fill="#183b56"/>
                      <path id="Shape-6" data-name="Shape" d="M.026,9.775A1,1,0,0,0,1,11H35.972a1,1,0,0,0,.974-1.225L34.69,0H2.281Z" transform="translate(13.514 38)" fill="#fff"/>
                      <path id="Shape-7" data-name="Shape" d="M1.626.777A1,1,0,0,1,2.6,0H13.4a1,1,0,0,1,.975.777l1.6,7A1,1,0,0,1,15,9H1A1,1,0,0,1,.026,7.777Z" transform="translate(24 42)" fill="#183b56"/>
                      <path id="Shape-8" data-name="Shape" d="M0,5H11.491L10.348,0H1.143Z" transform="translate(26.254 44)" fill="#ffc200"/>
                    </svg>
                    <h3 className='pt-5 text-base text-primary-text font-semibold'>Laptop</h3>
                </div>
              </div>

              <div className='group cursor-pointer'>
                <div className='grid justify-items-center px-5 py-5 rounded-lg border-2 group-hover:border-none hover:drop-shadow-2xl group-hover:bg-white'>
                  <svg id="iconspace_Not_C" data-name="iconspace_Not C" xmlns="http://www.w3.org/2000/svg" width="64" height="64" viewBox="0 0 64 64">
                    <circle id="Shape" cx="32" cy="32" r="32" fill="none"/>
                    <ellipse id="Shape-2" data-name="Shape" cx="6" cy="5" rx="6" ry="5" transform="translate(10 40)" fill="#fff"/>
                    <ellipse id="Shape-3" data-name="Shape" cx="6" cy="5" rx="6" ry="5" transform="translate(34 36)" fill="#fff"/>
                    <ellipse id="Shape-4" data-name="Shape" cx="6" cy="5" rx="6" ry="5" transform="translate(10 40)" fill="#36b37e"/>
                    <ellipse id="Shape-5" data-name="Shape" cx="6" cy="5" rx="6" ry="5" transform="translate(34 36)" fill="#ffc200"/>
                    <path id="Path" d="M7.5.158C4.912.713,3,2.67,3,5S4.912,9.287,7.5,9.842A7.152,7.152,0,0,1,6,10C2.686,10,0,7.761,0,5S2.686,0,6,0A7.152,7.152,0,0,1,7.5.158Z" transform="translate(10 40)" fill="#fff"/>
                    <path id="Shape-6" data-name="Shape" d="M7.5.158C4.912.713,3,2.67,3,5S4.912,9.287,7.5,9.842A7.152,7.152,0,0,1,6,10C2.686,10,0,7.761,0,5S2.686,0,6,0A7.152,7.152,0,0,1,7.5.158Z" transform="translate(34 36)" fill="#fff"/>
                    <path id="Shape-7" data-name="Shape" d="M0,6C0,2.641,3.17,0,7,0s7,2.641,7,6-3.171,6-7,6S0,9.358,0,6Z" transform="translate(9 39)" fill="#183b56"/>
                    <path id="Shape-8" data-name="Shape" d="M0,6C0,2.641,3.17,0,7,0s7,2.641,7,6-3.171,6-7,6S0,9.358,0,6Z" transform="translate(33 35)" fill="#183b56"/>
                    <path id="Shape-9" data-name="Shape" d="M2,8.713,24,2.332v28.33a1,1,0,0,0,2,0V1A1,1,0,0,0,24.721.04L.721,7A1,1,0,0,0,0,7.962v26.7a1,1,0,0,0,2,0Z" transform="translate(21 10.052)" fill="#183b56"/>
                    <path id="Shape-10" data-name="Shape" d="M0,13.947V7.961A1,1,0,0,1,.722,7l24-6.961A1,1,0,0,1,26,1V6.947a1,1,0,0,1-.72.96l-24,7A1,1,0,0,1,0,13.947Z" transform="translate(21 10.052)" fill="#154e84"/>
                  </svg>
                    <h3 className='pt-5 text-base text-primary-text font-semibold'>Music</h3>
                </div>
              </div>

              <div className='group cursor-pointer'>
                <div className='grid justify-items-center px-5 py-5 rounded-lg border-2 group-hover:border-none hover:drop-shadow-2xl group-hover:bg-white'>
                  <svg id="iconspace_Camera_" data-name="iconspace_Camera " xmlns="http://www.w3.org/2000/svg" width="64" height="64" viewBox="0 0 64 64">
                    <circle id="Shape" cx="32" cy="32" r="32" fill="none"/>
                    <path id="Shape-2" data-name="Shape" d="M9.42,7l3.136-5.488A3,3,0,0,1,15.161,0H26.839a3,3,0,0,1,2.6,1.512L32.58,7H39a3,3,0,0,1,3,3V35a3,3,0,0,1-3,3H3a3,3,0,0,1-3-3V10A3,3,0,0,1,3,7Z" transform="translate(11 13)" fill="#183b56"/>
                    <path id="Shape-3" data-name="Shape" d="M8,7H1A1,1,0,0,0,0,8V33a1,1,0,0,0,1,1H37a1,1,0,0,0,1-1V8a1,1,0,0,0-1-1H30a1,1,0,0,1-.868-.5L25.708.5a1,1,0,0,0-.868-.5H13.161a1,1,0,0,0-.868.5L8.868,6.5A1,1,0,0,1,8,7Z" transform="translate(13 15)" fill="#fff"/>
                    <path id="Shape-4" data-name="Shape" d="M-.766,0h16L12.525-4.514A1,1,0,0,0,11.668-5H2.8a1,1,0,0,0-.857.486Z" transform="translate(24.766 22)" fill="#36b37e"/>
                    <path id="Shape-5" data-name="Shape" d="M10,20A10,10,0,1,0,0,10,10,10,0,0,0,10,20Z" transform="translate(22 26)" fill="#183b56"/>
                    <path id="Shape-6" data-name="Shape" d="M8,16a8,8,0,1,1,8-8A8,8,0,0,1,8,16Z" transform="translate(24 28)" fill="#36b37e"/>
                    <circle id="Shape-7" data-name="Shape" cx="6" cy="6" r="6" transform="translate(26 30)" fill="#fff"/>
                    <circle id="Shape-8" data-name="Shape" cx="2" cy="2" r="2" transform="translate(16 25)" fill="#ffc200"/>
                  </svg>
                  <h3 className='pt-5 text-base text-primary-text font-semibold'>Photography</h3>
                </div>
              </div>

              <div className='group cursor-pointer'>
                <div className='grid justify-items-center px-5 py-5 rounded-lg border-2 group-hover:border-none hover:drop-shadow-2xl group-hover:bg-white'>
                  <svg id="iconspace_Chair" xmlns="http://www.w3.org/2000/svg" width="64" height="64" viewBox="0 0 64 64">
                    <circle id="Shape" cx="32" cy="32" r="32" fill="none"/>
                    <path id="Shape-2" data-name="Shape" d="M30,21a1,1,0,0,1-1,1H1a1,1,0,0,1-1-1V7A7,7,0,0,1,7,0H23a7,7,0,0,1,7,7Z" transform="translate(17 14)" fill="#183b56"/>
                    <path id="Shape-3" data-name="Shape" d="M26,18V5a5,5,0,0,0-5-5H5A5,5,0,0,0,0,5V18Z" transform="translate(19 16)" fill="#fff"/>
                    <path id="Shape-4" data-name="Shape" d="M0,5A5,5,0,0,1,10,5V21a1,1,0,0,1-1,1H5a3,3,0,0,1-3-3V9A5,5,0,0,1,0,5Z" transform="translate(11 24)" fill="#183b56"/>
                    <path id="Shape-5" data-name="Shape" d="M6,18V3A3,3,0,1,0,1.5,5.6a1,1,0,0,1,.5.866V17a1,1,0,0,0,1,1Z" transform="translate(13 26)" fill="#fff"/>
                    <path id="Shape-6" data-name="Shape" d="M0,5A5,5,0,0,0-5,0a5,5,0,0,0-5,5V21a1,1,0,0,0,1,1h4a3,3,0,0,0,3-3V9A5,5,0,0,0,0,5Z" transform="translate(53 24)" fill="#183b56"/>
                    <path id="Shape-7" data-name="Shape" d="M-6,18V3A3,3,0,0,1-3,0,3,3,0,0,1,0,3,3,3,0,0,1-1.5,5.6a1,1,0,0,0-.5.866V17a1,1,0,0,1-1,1Z" transform="translate(51 26)" fill="#fff"/>
                    <path id="Shape-8" data-name="Shape" d="M0,1A1,1,0,0,1,1,0H25a1,1,0,0,1,1,1V6a1,1,0,0,1-1,1H1A1,1,0,0,1,0,6Z" transform="translate(19 39)" fill="#154e84"/>
                    <path id="Shape-9" data-name="Shape" d="M0,0V3H22V0Z" transform="translate(21 41)" fill="#ffc200"/>
                    <path id="Shape-10" data-name="Shape" d="M0,1A1,1,0,0,1,1,0H5A1,1,0,0,1,6,1V4A2,2,0,0,1,4,6H2A2,2,0,0,1,0,4Z" transform="translate(15 44)" fill="#183b56"/>
                    <path id="Shape-11" data-name="Shape" d="M0,0V2H2V0Z" transform="translate(17 46)" fill="#36b37e"/>
                    <path id="Shape-12" data-name="Shape" d="M0,1A1,1,0,0,1,1,0H5A1,1,0,0,1,6,1V4A2,2,0,0,1,4,6H2A2,2,0,0,1,0,4Z" transform="translate(43 44)" fill="#183b56"/>
                    <path id="Shape-13" data-name="Shape" d="M0,0V2H2V0Z" transform="translate(45 46)" fill="#36b37e"/>
                    <path id="Shape-14" data-name="Shape" d="M0,1A1,1,0,0,1,1,0H25a1,1,0,0,1,1,1V6a1,1,0,0,1-1,1H1A1,1,0,0,1,0,6Z" transform="translate(19 34)" fill="#154e84"/>
                    <path id="Shape-15" data-name="Shape" d="M0,0V3H22V0Z" transform="translate(21 36)" fill="#36b37e"/>
                  </svg>
                  <h3 className='pt-5 text-base text-primary-text font-semibold'>Furniture</h3>
                </div>
              </div>

              <div className='group cursor-pointer'>
                <div className='grid justify-items-center px-5 py-5 rounded-lg border-2 group-hover:border-none hover:drop-shadow-2xl group-hover:bg-white'>
                <svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" viewBox="0 0 64 64">
                    <g id="iconspace_Stethoscope_B" data-name="iconspace_Stethoscope B" transform="translate(-2 -2)">
                      <circle id="Shape" cx="32" cy="32" r="32" transform="translate(2 2)" fill="none"/>
                      <path id="Shape-2" data-name="Shape" d="M20,4V6A9,9,0,0,1,2,6V0H0V6A11,11,0,0,0,22,6V4Z" transform="translate(27 38)" fill="#183b56"/>
                      <path id="Shape-3" data-name="Shape" d="M6,12A6,6,0,1,0,0,6,6,6,0,0,0,6,12Z" transform="translate(42 32)" fill="#183b56"/>
                      <path id="Shape-4" data-name="Shape" d="M4,8A4,4,0,1,1,8,4,4,4,0,0,1,4,8Z" transform="translate(44 34)" fill="#fff"/>
                      <circle id="Shape-5" data-name="Shape" cx="2" cy="2" r="2" transform="translate(46 36)" fill="#ffc200"/>
                      <path id="Shape-6" data-name="Shape" d="M19.323,5H17.436a1,1,0,0,1-1-1V1a1,1,0,0,1,1-1H21.88a3,3,0,0,1,2.912,3.721l-4.955,20A3,3,0,0,1,16.925,26h-8.9a3,3,0,0,1-2.91-2.269l-5.023-20A3,3,0,0,1,3,0H7.436a1,1,0,0,1,1,1V4a1,1,0,0,1-1,1H5.55L9.232,21H15.64Z" transform="translate(15.564 13)" fill="#183b56"/>
                      <path id="Shape-7" data-name="Shape" d="M4.436,0H1A1,1,0,0,0,.03,1.244l5.023,20a1,1,0,0,0,.97.756h8.9a1,1,0,0,0,.971-.76l4.955-20A1,1,0,0,0,19.88,0H16.436V1h2.143a1,1,0,0,1,.975,1.224l-4.143,18a1,1,0,0,1-.975.776h-8a1,1,0,0,1-.975-.776l-4.143-18A1,1,0,0,1,2.293,1H4.436Z" transform="translate(17.564 15)" fill="#36b37e"/>
                      <path id="Shape-8" data-name="Shape" d="M0,1A1,1,0,0,1,1,0H5A1,1,0,0,1,6,1V4A1,1,0,0,1,5,5H1A1,1,0,0,1,0,4Z" transform="translate(25 37)" fill="#183b56"/>
                      <path id="Shape-9" data-name="Shape" d="M0,0V1H2V0Z" transform="translate(27 39)" fill="#fff"/>
                    </g>
                  </svg>
                  <h3 className='pt-5 text-base text-primary-text font-semibold'>Health</h3>
                </div>
              </div>

              <div className='group cursor-pointer'>
                <div className='grid justify-items-center px-5 py-5 rounded-lg border-2 bg-accent-3 group-hover:border-none hover:drop-shadow-2xl group-hover:bg-white'>
                  <svg id="iconspace_Apps" xmlns="http://www.w3.org/2000/svg" width="64" height="64" viewBox="0 0 64 64">
                    <circle id="Oval" cx="32" cy="32" r="32" fill="none"/>
                    <path id="Shape" d="M3,0H13a3,3,0,0,1,3,3V13a3,3,0,0,1-3,3H3a3,3,0,0,1-3-3V3A3,3,0,0,1,3,0Z" transform="translate(13 14)" fill="#183b56"/>
                    <path id="Shape-2" data-name="Shape" d="M1,0A1,1,0,0,0,0,1V11a1,1,0,0,0,1,1H11a1,1,0,0,0,1-1V1a1,1,0,0,0-1-1Z" transform="translate(15 16)" fill="#ffc200"/>
                    <path id="Shape-3" data-name="Shape" d="M3,0H13a3,3,0,0,1,3,3V13a3,3,0,0,1-3,3H3a3,3,0,0,1-3-3V3A3,3,0,0,1,3,0Z" transform="translate(35 14)" fill="#183b56"/>
                    <path id="Shape-4" data-name="Shape" d="M1,0A1,1,0,0,0,0,1V11a1,1,0,0,0,1,1H11a1,1,0,0,0,1-1V1a1,1,0,0,0-1-1Z" transform="translate(37 16)" fill="#fff"/>
                    <path id="Shape-5" data-name="Shape" d="M3,0H13a3,3,0,0,1,3,3V13a3,3,0,0,1-3,3H3a3,3,0,0,1-3-3V3A3,3,0,0,1,3,0Z" transform="translate(13 35)" fill="#183b56"/>
                    <path id="Shape-6" data-name="Shape" d="M1,0A1,1,0,0,0,0,1V11a1,1,0,0,0,1,1H11a1,1,0,0,0,1-1V1a1,1,0,0,0-1-1Z" transform="translate(15 37)" fill="#fff"/>
                    <path id="Shape-7" data-name="Shape" d="M3,0H13a3,3,0,0,1,3,3V13a3,3,0,0,1-3,3H3a3,3,0,0,1-3-3V3A3,3,0,0,1,3,0Z" transform="translate(35 35)" fill="#183b56"/>
                    <path id="Shape-8" data-name="Shape" d="M1,0A1,1,0,0,0,0,1V11a1,1,0,0,0,1,1H11a1,1,0,0,0,1-1V1a1,1,0,0,0-1-1Z" transform="translate(37 37)" fill="#36b37e"/>
                  </svg>
                  <h3 className='pt-5 text-base text-primary-text font-semibold'>More</h3>
                </div>
              </div>
            </div>
          </section>

          {/* Stats */}
          <section className='relative container flex flex-row mx-auto overflow-x-auto bg-white'>
            <div className='flex-auto py-2'>
              <div className='w-auto flex flex-row gap-4 items-start px-4 py-3'>
                <div className='flex flex-col w-72'>
                  <h3 className='mb-5 text-xl text-primary-text font-semibold'>Most Sold Laptops</h3>
                  
                  <div className='flex flex-col gap-4'>
                    {/* item wrapper */}
                    <div className='px-5 pt-4 pb-5 rounded-lg bg-primary-3'>
                      <div className='grid justify-items-start'>
                        <div className=' w-16 h-16 rounded-lg bg-red-500'></div>
                      </div>
                      <h4 className='mt-4 font-semibold'>Asus Zenbook Pro 13"</h4>
                      <div className='flex flex-row'>
                        <div className='flex flex-row items-center justify-items-center content-center gap-1'>
                          <svg xmlns="http://www.w3.org/2000/svg" width="14.629" height="14.002" viewBox="0 0 14.629 14.002">
                            <path id="star" d="M3.741,13.9l3.574-1.879L10.888,13.9a.875.875,0,0,0,1.269-.921L11.473,9l2.89-2.816A.875.875,0,0,0,13.88,4.69L9.885,4.107,8.1.487a.876.876,0,0,0-1.57,0L4.744,4.107.749,4.69A.875.875,0,0,0,.265,6.183L3.155,9l-.684,3.979A.874.874,0,0,0,3.741,13.9Z" transform="translate(0)" fill="#ffc200"/>
                          </svg>
                          <span className='text-sm text-primary-text'>4.8</span>
                        </div>
                        <div className='flex flex-row items-center justify-items-center content-center mx-3'>
                          <svg id="Elements_Shape_Fill_99_R" data-name="Elements/Shape/Fill/99 R" xmlns="http://www.w3.org/2000/svg" width="4" height="4" viewBox="0 0 4 4">
                            <rect id="Shadow" width="4" height="4" rx="2" fill="none"/>
                            <rect id="Fill" width="4" height="4" rx="2" fill="#b3bac5"/>
                          </svg>
                        </div>
                        <div className='flex flex-row items-center justify-items-center content-center gap-1'>
                          <svg id="iconspace_Stroller_25px" xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 18 18">
                            <path id="path" d="M0,0H18V18H0Z" fill="none"/>
                            <path id="path-2" data-name="path" d="M11.485,14.58a1.621,1.621,0,0,1-1.526-2.159H7.976a1.618,1.618,0,1,1-2.754-.516A2.7,2.7,0,0,1,4.126,10l-.008-.081A2.535,2.535,0,0,1,2.5,7.783L2.287,5.3a.44.44,0,0,1-.008-.048L2.046,2.97l-.13-1.083a.9.9,0,0,0-.895-.807H.54A.54.54,0,0,1,.54,0h.482A1.974,1.974,0,0,1,2.99,1.777l.1.961H14.04a.359.359,0,0,1,.353.429l-.957,4.881a2.522,2.522,0,0,1-2.47,2.034H5.231a1.63,1.63,0,0,0,1.579,1.259h4.517a.191.191,0,0,1,.043,0H11.4l.087,0a1.619,1.619,0,0,1,0,3.238Zm0-2.339a.72.72,0,1,0,.72.72A.72.72,0,0,0,11.485,12.241Zm-5.036,0a.72.72,0,1,0,.72.72A.72.72,0,0,0,6.449,12.241Z" transform="translate(2.16 1.44)" fill="#5a7184"/>
                          </svg>
                          <span className='text-sm text-secondary-text'>2,1k Unit Sold</span>
                        </div>
                      </div>
                    </div>

                    <div className='px-5 pt-4 pb-5 rounded-lg bg-primary-3'>
                      <div className='grid justify-items-start'>
                        <div className=' w-16 h-16 rounded-lg bg-red-500'></div>
                      </div>
                      <h4 className='mt-4 font-semibold'>Asus Zenbook Pro 13"</h4>
                      <div className='flex flex-row'>
                        <div className='flex flex-row items-center justify-items-center content-center gap-1'>
                          <svg xmlns="http://www.w3.org/2000/svg" width="14.629" height="14.002" viewBox="0 0 14.629 14.002">
                            <path id="star" d="M3.741,13.9l3.574-1.879L10.888,13.9a.875.875,0,0,0,1.269-.921L11.473,9l2.89-2.816A.875.875,0,0,0,13.88,4.69L9.885,4.107,8.1.487a.876.876,0,0,0-1.57,0L4.744,4.107.749,4.69A.875.875,0,0,0,.265,6.183L3.155,9l-.684,3.979A.874.874,0,0,0,3.741,13.9Z" transform="translate(0)" fill="#ffc200"/>
                          </svg>
                          <span className='text-sm text-primary-text'>4.8</span>
                        </div>
                        <div className='flex flex-row items-center justify-items-center content-center mx-3'>
                          <svg id="Elements_Shape_Fill_99_R" data-name="Elements/Shape/Fill/99 R" xmlns="http://www.w3.org/2000/svg" width="4" height="4" viewBox="0 0 4 4">
                            <rect id="Shadow" width="4" height="4" rx="2" fill="none"/>
                            <rect id="Fill" width="4" height="4" rx="2" fill="#b3bac5"/>
                          </svg>
                        </div>
                        <div className='flex flex-row items-center justify-items-center content-center gap-1'>
                          <svg id="iconspace_Stroller_25px" xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 18 18">
                            <path id="path" d="M0,0H18V18H0Z" fill="none"/>
                            <path id="path-2" data-name="path" d="M11.485,14.58a1.621,1.621,0,0,1-1.526-2.159H7.976a1.618,1.618,0,1,1-2.754-.516A2.7,2.7,0,0,1,4.126,10l-.008-.081A2.535,2.535,0,0,1,2.5,7.783L2.287,5.3a.44.44,0,0,1-.008-.048L2.046,2.97l-.13-1.083a.9.9,0,0,0-.895-.807H.54A.54.54,0,0,1,.54,0h.482A1.974,1.974,0,0,1,2.99,1.777l.1.961H14.04a.359.359,0,0,1,.353.429l-.957,4.881a2.522,2.522,0,0,1-2.47,2.034H5.231a1.63,1.63,0,0,0,1.579,1.259h4.517a.191.191,0,0,1,.043,0H11.4l.087,0a1.619,1.619,0,0,1,0,3.238Zm0-2.339a.72.72,0,1,0,.72.72A.72.72,0,0,0,11.485,12.241Zm-5.036,0a.72.72,0,1,0,.72.72A.72.72,0,0,0,6.449,12.241Z" transform="translate(2.16 1.44)" fill="#5a7184"/>
                          </svg>
                          <span className='text-sm text-secondary-text'>2,1k Unit Sold</span>
                        </div>
                      </div>
                    </div>

                    <div className='px-5 pt-4 pb-5 rounded-lg bg-primary-3'>
                      <div className='grid justify-items-start'>
                        <div className=' w-16 h-16 rounded-lg bg-red-500'></div>
                      </div>
                      <h4 className='mt-4 font-semibold'>Asus Zenbook Pro 13"</h4>
                      <div className='flex flex-row'>
                        <div className='flex flex-row items-center justify-items-center content-center gap-1'>
                          <svg xmlns="http://www.w3.org/2000/svg" width="14.629" height="14.002" viewBox="0 0 14.629 14.002">
                            <path id="star" d="M3.741,13.9l3.574-1.879L10.888,13.9a.875.875,0,0,0,1.269-.921L11.473,9l2.89-2.816A.875.875,0,0,0,13.88,4.69L9.885,4.107,8.1.487a.876.876,0,0,0-1.57,0L4.744,4.107.749,4.69A.875.875,0,0,0,.265,6.183L3.155,9l-.684,3.979A.874.874,0,0,0,3.741,13.9Z" transform="translate(0)" fill="#ffc200"/>
                          </svg>
                          <span className='text-sm text-primary-text'>4.8</span>
                        </div>
                        <div className='flex flex-row items-center justify-items-center content-center mx-3'>
                          <svg id="Elements_Shape_Fill_99_R" data-name="Elements/Shape/Fill/99 R" xmlns="http://www.w3.org/2000/svg" width="4" height="4" viewBox="0 0 4 4">
                            <rect id="Shadow" width="4" height="4" rx="2" fill="none"/>
                            <rect id="Fill" width="4" height="4" rx="2" fill="#b3bac5"/>
                          </svg>
                        </div>
                        <div className='flex flex-row items-center justify-items-center content-center gap-1'>
                          <svg id="iconspace_Stroller_25px" xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 18 18">
                            <path id="path" d="M0,0H18V18H0Z" fill="none"/>
                            <path id="path-2" data-name="path" d="M11.485,14.58a1.621,1.621,0,0,1-1.526-2.159H7.976a1.618,1.618,0,1,1-2.754-.516A2.7,2.7,0,0,1,4.126,10l-.008-.081A2.535,2.535,0,0,1,2.5,7.783L2.287,5.3a.44.44,0,0,1-.008-.048L2.046,2.97l-.13-1.083a.9.9,0,0,0-.895-.807H.54A.54.54,0,0,1,.54,0h.482A1.974,1.974,0,0,1,2.99,1.777l.1.961H14.04a.359.359,0,0,1,.353.429l-.957,4.881a2.522,2.522,0,0,1-2.47,2.034H5.231a1.63,1.63,0,0,0,1.579,1.259h4.517a.191.191,0,0,1,.043,0H11.4l.087,0a1.619,1.619,0,0,1,0,3.238Zm0-2.339a.72.72,0,1,0,.72.72A.72.72,0,0,0,11.485,12.241Zm-5.036,0a.72.72,0,1,0,.72.72A.72.72,0,0,0,6.449,12.241Z" transform="translate(2.16 1.44)" fill="#5a7184"/>
                          </svg>
                          <span className='text-sm text-secondary-text'>2,1k Unit Sold</span>
                        </div>
                      </div>
                    </div>
                  </div>

                  <div className='flex flex-row items-center justify-items-center content-center px-5 py-5'>
                    <p className='flex-auto text-secondary font-bold'>Leaderboard details</p>
                    <span>
                      <svg xmlns="http://www.w3.org/2000/svg" width="7.246" height="11.941" viewBox="0 0 7.246 11.941">
                        <path id="chevron-right" d="M1.74,11.748,7.054,6.434a.656.656,0,0,0,0-.928L1.74.192a.656.656,0,0,0-.928,0l-.62.62a.656.656,0,0,0,0,.927L4.4,5.97.191,10.2a.656.656,0,0,0,0,.927l.62.62A.656.656,0,0,0,1.74,11.748Z" fill="#36b37e"/>
                      </svg>
                    </span>
                  </div>
                </div>
                
                <div className='flex flex-col w-72'>
                  <h3 className='mb-5 text-xl text-primary-text font-semibold'>Most Sold Cameras</h3>
                  
                  <div className='flex flex-col gap-4'>
                    {/* item wrapper */}
                    <div className='px-5 pt-4 pb-5 rounded-lg bg-primary-3'>
                      <div className='grid justify-items-start'>
                        <div className=' w-16 h-16 rounded-lg bg-red-500'></div>
                      </div>
                      <h4 className='mt-4 font-semibold'>Asus Zenbook Pro 13"</h4>
                      <div className='flex flex-row'>
                        <div className='flex flex-row items-center justify-items-center content-center gap-1'>
                          <svg xmlns="http://www.w3.org/2000/svg" width="14.629" height="14.002" viewBox="0 0 14.629 14.002">
                            <path id="star" d="M3.741,13.9l3.574-1.879L10.888,13.9a.875.875,0,0,0,1.269-.921L11.473,9l2.89-2.816A.875.875,0,0,0,13.88,4.69L9.885,4.107,8.1.487a.876.876,0,0,0-1.57,0L4.744,4.107.749,4.69A.875.875,0,0,0,.265,6.183L3.155,9l-.684,3.979A.874.874,0,0,0,3.741,13.9Z" transform="translate(0)" fill="#ffc200"/>
                          </svg>
                          <span className='text-sm text-primary-text'>4.8</span>
                        </div>
                        <div className='flex flex-row items-center justify-items-center content-center mx-3'>
                          <svg id="Elements_Shape_Fill_99_R" data-name="Elements/Shape/Fill/99 R" xmlns="http://www.w3.org/2000/svg" width="4" height="4" viewBox="0 0 4 4">
                            <rect id="Shadow" width="4" height="4" rx="2" fill="none"/>
                            <rect id="Fill" width="4" height="4" rx="2" fill="#b3bac5"/>
                          </svg>
                        </div>
                        <div className='flex flex-row items-center justify-items-center content-center gap-1'>
                          <svg id="iconspace_Stroller_25px" xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 18 18">
                            <path id="path" d="M0,0H18V18H0Z" fill="none"/>
                            <path id="path-2" data-name="path" d="M11.485,14.58a1.621,1.621,0,0,1-1.526-2.159H7.976a1.618,1.618,0,1,1-2.754-.516A2.7,2.7,0,0,1,4.126,10l-.008-.081A2.535,2.535,0,0,1,2.5,7.783L2.287,5.3a.44.44,0,0,1-.008-.048L2.046,2.97l-.13-1.083a.9.9,0,0,0-.895-.807H.54A.54.54,0,0,1,.54,0h.482A1.974,1.974,0,0,1,2.99,1.777l.1.961H14.04a.359.359,0,0,1,.353.429l-.957,4.881a2.522,2.522,0,0,1-2.47,2.034H5.231a1.63,1.63,0,0,0,1.579,1.259h4.517a.191.191,0,0,1,.043,0H11.4l.087,0a1.619,1.619,0,0,1,0,3.238Zm0-2.339a.72.72,0,1,0,.72.72A.72.72,0,0,0,11.485,12.241Zm-5.036,0a.72.72,0,1,0,.72.72A.72.72,0,0,0,6.449,12.241Z" transform="translate(2.16 1.44)" fill="#5a7184"/>
                          </svg>
                          <span className='text-sm text-secondary-text'>2,1k Unit Sold</span>
                        </div>
                      </div>
                    </div>

                    <div className='px-5 pt-4 pb-5 rounded-lg bg-primary-3'>
                      <div className='grid justify-items-start'>
                        <div className=' w-16 h-16 rounded-lg bg-red-500'></div>
                      </div>
                      <h4 className='mt-4 font-semibold'>Asus Zenbook Pro 13"</h4>
                      <div className='flex flex-row'>
                        <div className='flex flex-row items-center justify-items-center content-center gap-1'>
                          <svg xmlns="http://www.w3.org/2000/svg" width="14.629" height="14.002" viewBox="0 0 14.629 14.002">
                            <path id="star" d="M3.741,13.9l3.574-1.879L10.888,13.9a.875.875,0,0,0,1.269-.921L11.473,9l2.89-2.816A.875.875,0,0,0,13.88,4.69L9.885,4.107,8.1.487a.876.876,0,0,0-1.57,0L4.744,4.107.749,4.69A.875.875,0,0,0,.265,6.183L3.155,9l-.684,3.979A.874.874,0,0,0,3.741,13.9Z" transform="translate(0)" fill="#ffc200"/>
                          </svg>
                          <span className='text-sm text-primary-text'>4.8</span>
                        </div>
                        <div className='flex flex-row items-center justify-items-center content-center mx-3'>
                          <svg id="Elements_Shape_Fill_99_R" data-name="Elements/Shape/Fill/99 R" xmlns="http://www.w3.org/2000/svg" width="4" height="4" viewBox="0 0 4 4">
                            <rect id="Shadow" width="4" height="4" rx="2" fill="none"/>
                            <rect id="Fill" width="4" height="4" rx="2" fill="#b3bac5"/>
                          </svg>
                        </div>
                        <div className='flex flex-row items-center justify-items-center content-center gap-1'>
                          <svg id="iconspace_Stroller_25px" xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 18 18">
                            <path id="path" d="M0,0H18V18H0Z" fill="none"/>
                            <path id="path-2" data-name="path" d="M11.485,14.58a1.621,1.621,0,0,1-1.526-2.159H7.976a1.618,1.618,0,1,1-2.754-.516A2.7,2.7,0,0,1,4.126,10l-.008-.081A2.535,2.535,0,0,1,2.5,7.783L2.287,5.3a.44.44,0,0,1-.008-.048L2.046,2.97l-.13-1.083a.9.9,0,0,0-.895-.807H.54A.54.54,0,0,1,.54,0h.482A1.974,1.974,0,0,1,2.99,1.777l.1.961H14.04a.359.359,0,0,1,.353.429l-.957,4.881a2.522,2.522,0,0,1-2.47,2.034H5.231a1.63,1.63,0,0,0,1.579,1.259h4.517a.191.191,0,0,1,.043,0H11.4l.087,0a1.619,1.619,0,0,1,0,3.238Zm0-2.339a.72.72,0,1,0,.72.72A.72.72,0,0,0,11.485,12.241Zm-5.036,0a.72.72,0,1,0,.72.72A.72.72,0,0,0,6.449,12.241Z" transform="translate(2.16 1.44)" fill="#5a7184"/>
                          </svg>
                          <span className='text-sm text-secondary-text'>2,1k Unit Sold</span>
                        </div>
                      </div>
                    </div>

                    <div className='px-5 pt-4 pb-5 rounded-lg bg-primary-3'>
                      <div className='grid justify-items-start'>
                        <div className=' w-16 h-16 rounded-lg bg-red-500'></div>
                      </div>
                      <h4 className='mt-4 font-semibold'>Asus Zenbook Pro 13"</h4>
                      <div className='flex flex-row'>
                        <div className='flex flex-row items-center justify-items-center content-center gap-1'>
                          <svg xmlns="http://www.w3.org/2000/svg" width="14.629" height="14.002" viewBox="0 0 14.629 14.002">
                            <path id="star" d="M3.741,13.9l3.574-1.879L10.888,13.9a.875.875,0,0,0,1.269-.921L11.473,9l2.89-2.816A.875.875,0,0,0,13.88,4.69L9.885,4.107,8.1.487a.876.876,0,0,0-1.57,0L4.744,4.107.749,4.69A.875.875,0,0,0,.265,6.183L3.155,9l-.684,3.979A.874.874,0,0,0,3.741,13.9Z" transform="translate(0)" fill="#ffc200"/>
                          </svg>
                          <span className='text-sm text-primary-text'>4.8</span>
                        </div>
                        <div className='flex flex-row items-center justify-items-center content-center mx-3'>
                          <svg id="Elements_Shape_Fill_99_R" data-name="Elements/Shape/Fill/99 R" xmlns="http://www.w3.org/2000/svg" width="4" height="4" viewBox="0 0 4 4">
                            <rect id="Shadow" width="4" height="4" rx="2" fill="none"/>
                            <rect id="Fill" width="4" height="4" rx="2" fill="#b3bac5"/>
                          </svg>
                        </div>
                        <div className='flex flex-row items-center justify-items-center content-center gap-1'>
                          <svg id="iconspace_Stroller_25px" xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 18 18">
                            <path id="path" d="M0,0H18V18H0Z" fill="none"/>
                            <path id="path-2" data-name="path" d="M11.485,14.58a1.621,1.621,0,0,1-1.526-2.159H7.976a1.618,1.618,0,1,1-2.754-.516A2.7,2.7,0,0,1,4.126,10l-.008-.081A2.535,2.535,0,0,1,2.5,7.783L2.287,5.3a.44.44,0,0,1-.008-.048L2.046,2.97l-.13-1.083a.9.9,0,0,0-.895-.807H.54A.54.54,0,0,1,.54,0h.482A1.974,1.974,0,0,1,2.99,1.777l.1.961H14.04a.359.359,0,0,1,.353.429l-.957,4.881a2.522,2.522,0,0,1-2.47,2.034H5.231a1.63,1.63,0,0,0,1.579,1.259h4.517a.191.191,0,0,1,.043,0H11.4l.087,0a1.619,1.619,0,0,1,0,3.238Zm0-2.339a.72.72,0,1,0,.72.72A.72.72,0,0,0,11.485,12.241Zm-5.036,0a.72.72,0,1,0,.72.72A.72.72,0,0,0,6.449,12.241Z" transform="translate(2.16 1.44)" fill="#5a7184"/>
                          </svg>
                          <span className='text-sm text-secondary-text'>2,1k Unit Sold</span>
                        </div>
                      </div>
                    </div>
                  </div>

                  <div className='flex flex-row items-center justify-items-center content-center px-5 py-5'>
                    <p className='flex-auto text-secondary font-bold'>Leaderboard details</p>
                    <span>
                      <svg xmlns="http://www.w3.org/2000/svg" width="7.246" height="11.941" viewBox="0 0 7.246 11.941">
                        <path id="chevron-right" d="M1.74,11.748,7.054,6.434a.656.656,0,0,0,0-.928L1.74.192a.656.656,0,0,0-.928,0l-.62.62a.656.656,0,0,0,0,.927L4.4,5.97.191,10.2a.656.656,0,0,0,0,.927l.62.62A.656.656,0,0,0,1.74,11.748Z" fill="#36b37e"/>
                      </svg>
                    </span>
                  </div>
                </div>

                <div className='flex flex-col w-72'>
                  <h3 className='mb-5 text-xl text-primary-text font-semibold'>Most Sold Headphones</h3>
                  
                  <div className='flex flex-col gap-4'>
                    {/* item wrapper */}
                    <div className='px-5 pt-4 pb-5 rounded-lg bg-primary-3'>
                      <div className='grid justify-items-start'>
                        <div className=' w-16 h-16 rounded-lg bg-red-500'></div>
                      </div>
                      <h4 className='mt-4 font-semibold'>Asus Zenbook Pro 13"</h4>
                      <div className='flex flex-row'>
                        <div className='flex flex-row items-center justify-items-center content-center gap-1'>
                          <svg xmlns="http://www.w3.org/2000/svg" width="14.629" height="14.002" viewBox="0 0 14.629 14.002">
                            <path id="star" d="M3.741,13.9l3.574-1.879L10.888,13.9a.875.875,0,0,0,1.269-.921L11.473,9l2.89-2.816A.875.875,0,0,0,13.88,4.69L9.885,4.107,8.1.487a.876.876,0,0,0-1.57,0L4.744,4.107.749,4.69A.875.875,0,0,0,.265,6.183L3.155,9l-.684,3.979A.874.874,0,0,0,3.741,13.9Z" transform="translate(0)" fill="#ffc200"/>
                          </svg>
                          <span className='text-sm text-primary-text'>4.8</span>
                        </div>
                        <div className='flex flex-row items-center justify-items-center content-center mx-3'>
                          <svg id="Elements_Shape_Fill_99_R" data-name="Elements/Shape/Fill/99 R" xmlns="http://www.w3.org/2000/svg" width="4" height="4" viewBox="0 0 4 4">
                            <rect id="Shadow" width="4" height="4" rx="2" fill="none"/>
                            <rect id="Fill" width="4" height="4" rx="2" fill="#b3bac5"/>
                          </svg>
                        </div>
                        <div className='flex flex-row items-center justify-items-center content-center gap-1'>
                          <svg id="iconspace_Stroller_25px" xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 18 18">
                            <path id="path" d="M0,0H18V18H0Z" fill="none"/>
                            <path id="path-2" data-name="path" d="M11.485,14.58a1.621,1.621,0,0,1-1.526-2.159H7.976a1.618,1.618,0,1,1-2.754-.516A2.7,2.7,0,0,1,4.126,10l-.008-.081A2.535,2.535,0,0,1,2.5,7.783L2.287,5.3a.44.44,0,0,1-.008-.048L2.046,2.97l-.13-1.083a.9.9,0,0,0-.895-.807H.54A.54.54,0,0,1,.54,0h.482A1.974,1.974,0,0,1,2.99,1.777l.1.961H14.04a.359.359,0,0,1,.353.429l-.957,4.881a2.522,2.522,0,0,1-2.47,2.034H5.231a1.63,1.63,0,0,0,1.579,1.259h4.517a.191.191,0,0,1,.043,0H11.4l.087,0a1.619,1.619,0,0,1,0,3.238Zm0-2.339a.72.72,0,1,0,.72.72A.72.72,0,0,0,11.485,12.241Zm-5.036,0a.72.72,0,1,0,.72.72A.72.72,0,0,0,6.449,12.241Z" transform="translate(2.16 1.44)" fill="#5a7184"/>
                          </svg>
                          <span className='text-sm text-secondary-text'>2,1k Unit Sold</span>
                        </div>
                      </div>
                    </div>

                    <div className='px-5 pt-4 pb-5 rounded-lg bg-primary-3'>
                      <div className='grid justify-items-start'>
                        <div className=' w-16 h-16 rounded-lg bg-red-500'></div>
                      </div>
                      <h4 className='mt-4 font-semibold'>Asus Zenbook Pro 13"</h4>
                      <div className='flex flex-row'>
                        <div className='flex flex-row items-center justify-items-center content-center gap-1'>
                          <svg xmlns="http://www.w3.org/2000/svg" width="14.629" height="14.002" viewBox="0 0 14.629 14.002">
                            <path id="star" d="M3.741,13.9l3.574-1.879L10.888,13.9a.875.875,0,0,0,1.269-.921L11.473,9l2.89-2.816A.875.875,0,0,0,13.88,4.69L9.885,4.107,8.1.487a.876.876,0,0,0-1.57,0L4.744,4.107.749,4.69A.875.875,0,0,0,.265,6.183L3.155,9l-.684,3.979A.874.874,0,0,0,3.741,13.9Z" transform="translate(0)" fill="#ffc200"/>
                          </svg>
                          <span className='text-sm text-primary-text'>4.8</span>
                        </div>
                        <div className='flex flex-row items-center justify-items-center content-center mx-3'>
                          <svg id="Elements_Shape_Fill_99_R" data-name="Elements/Shape/Fill/99 R" xmlns="http://www.w3.org/2000/svg" width="4" height="4" viewBox="0 0 4 4">
                            <rect id="Shadow" width="4" height="4" rx="2" fill="none"/>
                            <rect id="Fill" width="4" height="4" rx="2" fill="#b3bac5"/>
                          </svg>
                        </div>
                        <div className='flex flex-row items-center justify-items-center content-center gap-1'>
                          <svg id="iconspace_Stroller_25px" xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 18 18">
                            <path id="path" d="M0,0H18V18H0Z" fill="none"/>
                            <path id="path-2" data-name="path" d="M11.485,14.58a1.621,1.621,0,0,1-1.526-2.159H7.976a1.618,1.618,0,1,1-2.754-.516A2.7,2.7,0,0,1,4.126,10l-.008-.081A2.535,2.535,0,0,1,2.5,7.783L2.287,5.3a.44.44,0,0,1-.008-.048L2.046,2.97l-.13-1.083a.9.9,0,0,0-.895-.807H.54A.54.54,0,0,1,.54,0h.482A1.974,1.974,0,0,1,2.99,1.777l.1.961H14.04a.359.359,0,0,1,.353.429l-.957,4.881a2.522,2.522,0,0,1-2.47,2.034H5.231a1.63,1.63,0,0,0,1.579,1.259h4.517a.191.191,0,0,1,.043,0H11.4l.087,0a1.619,1.619,0,0,1,0,3.238Zm0-2.339a.72.72,0,1,0,.72.72A.72.72,0,0,0,11.485,12.241Zm-5.036,0a.72.72,0,1,0,.72.72A.72.72,0,0,0,6.449,12.241Z" transform="translate(2.16 1.44)" fill="#5a7184"/>
                          </svg>
                          <span className='text-sm text-secondary-text'>2,1k Unit Sold</span>
                        </div>
                      </div>
                    </div>

                    <div className='px-5 pt-4 pb-5 rounded-lg bg-primary-3'>
                      <div className='grid justify-items-start'>
                        <div className=' w-16 h-16 rounded-lg bg-red-500'></div>
                      </div>
                      <h4 className='mt-4 font-semibold'>Asus Zenbook Pro 13"</h4>
                      <div className='flex flex-row'>
                        <div className='flex flex-row items-center justify-items-center content-center gap-1'>
                          <svg xmlns="http://www.w3.org/2000/svg" width="14.629" height="14.002" viewBox="0 0 14.629 14.002">
                            <path id="star" d="M3.741,13.9l3.574-1.879L10.888,13.9a.875.875,0,0,0,1.269-.921L11.473,9l2.89-2.816A.875.875,0,0,0,13.88,4.69L9.885,4.107,8.1.487a.876.876,0,0,0-1.57,0L4.744,4.107.749,4.69A.875.875,0,0,0,.265,6.183L3.155,9l-.684,3.979A.874.874,0,0,0,3.741,13.9Z" transform="translate(0)" fill="#ffc200"/>
                          </svg>
                          <span className='text-sm text-primary-text'>4.8</span>
                        </div>
                        <div className='flex flex-row items-center justify-items-center content-center mx-3'>
                          <svg id="Elements_Shape_Fill_99_R" data-name="Elements/Shape/Fill/99 R" xmlns="http://www.w3.org/2000/svg" width="4" height="4" viewBox="0 0 4 4">
                            <rect id="Shadow" width="4" height="4" rx="2" fill="none"/>
                            <rect id="Fill" width="4" height="4" rx="2" fill="#b3bac5"/>
                          </svg>
                        </div>
                        <div className='flex flex-row items-center justify-items-center content-center gap-1'>
                          <svg id="iconspace_Stroller_25px" xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 18 18">
                            <path id="path" d="M0,0H18V18H0Z" fill="none"/>
                            <path id="path-2" data-name="path" d="M11.485,14.58a1.621,1.621,0,0,1-1.526-2.159H7.976a1.618,1.618,0,1,1-2.754-.516A2.7,2.7,0,0,1,4.126,10l-.008-.081A2.535,2.535,0,0,1,2.5,7.783L2.287,5.3a.44.44,0,0,1-.008-.048L2.046,2.97l-.13-1.083a.9.9,0,0,0-.895-.807H.54A.54.54,0,0,1,.54,0h.482A1.974,1.974,0,0,1,2.99,1.777l.1.961H14.04a.359.359,0,0,1,.353.429l-.957,4.881a2.522,2.522,0,0,1-2.47,2.034H5.231a1.63,1.63,0,0,0,1.579,1.259h4.517a.191.191,0,0,1,.043,0H11.4l.087,0a1.619,1.619,0,0,1,0,3.238Zm0-2.339a.72.72,0,1,0,.72.72A.72.72,0,0,0,11.485,12.241Zm-5.036,0a.72.72,0,1,0,.72.72A.72.72,0,0,0,6.449,12.241Z" transform="translate(2.16 1.44)" fill="#5a7184"/>
                          </svg>
                          <span className='text-sm text-secondary-text'>2,1k Unit Sold</span>
                        </div>
                      </div>
                    </div>
                  </div>

                  <div className='flex flex-row items-center justify-items-center content-center px-5 py-5'>
                    <p className='flex-auto text-secondary font-bold'>Leaderboard details</p>
                    <span>
                      <svg xmlns="http://www.w3.org/2000/svg" width="7.246" height="11.941" viewBox="0 0 7.246 11.941">
                        <path id="chevron-right" d="M1.74,11.748,7.054,6.434a.656.656,0,0,0,0-.928L1.74.192a.656.656,0,0,0-.928,0l-.62.62a.656.656,0,0,0,0,.927L4.4,5.97.191,10.2a.656.656,0,0,0,0,.927l.62.62A.656.656,0,0,0,1.74,11.748Z" fill="#36b37e"/>
                      </svg>
                    </span>
                  </div>
                </div>
              </div>
            </div>
          </section>

          {/* Blogs */}
          <section className='flex flex-col container mx-auto px-5 pb-9 bg-white'>
            <div className='flex flex-col text-center pt-24 border-t-2'>
              <h3 className='text-center text-3xl'>📝<span>Read Our Blog</span></h3>
              <p className='mt-6 mb-9 text-base text-secondary-text'>Check our latest article to get an inspiring content for shopping</p>
            </div>

            <div className='flex flex-col gap-4'>
              <article className='flex flex-col px-4 py-4 bg-accent-3 rounded-lg'>
                <div className='relative flex flex-row items-center justify-items-center content-center justify-center w-60 h-32 rounded-lg bg-special'>
                  <div className='absolute top-4 right-4 w-9 h-9 rounded-full bg-white z-0'>
                      <div className='w-9 h-9 bg-accent-3 rounded-full flex items-center justify-items-center content-center justify-center'>
                        <svg xmlns="http://www.w3.org/2000/svg" width="10.4" height="13.365" viewBox="0 0 10.4 13.365">
                          <path id="Path" d="M2.8,0H7.6a2.8,2.8,0,0,1,2.8,2.8v9.365a1.2,1.2,0,0,1-1.969.921L5.456,10.6a.4.4,0,0,0-.512,0L1.969,13.086A1.2,1.2,0,0,1,0,12.165V2.8A2.8,2.8,0,0,1,2.8,0Z" fill="#5a7184"/>
                        </svg>
                      </div>
                  </div>
                </div>
                <div>
                  <h4 className='pt-5 pb-2 text-lg text-primary-text'>Brighten Up Dull Tired Skin</h4>
                  <p className='mb-4 text-sm'>Gravity is an irresistible force. While it is certainly nice that…</p>
                  <span className='flex flex-row items-center justify-items-center content-center justify-start gap-4'>
                    <span className='text-base text-secondary font-semibold'>Read More</span>
                    <span>
                      <svg xmlns="http://www.w3.org/2000/svg" width="12.251" height="11.941" viewBox="0 0 12.251 11.941">
                        <path id="arrow-right" d="M6.743,11.748l5.316-5.316a.654.654,0,0,0,0-.927L6.743.193a.654.654,0,0,0-.927,0L5.209.8a.652.652,0,0,0,.011.938L8.515,4.877H.656A.655.655,0,0,0,0,5.533v.875a.655.655,0,0,0,.656.656H8.515L5.22,10.2a.657.657,0,0,0-.011.938l.607.607A.654.654,0,0,0,6.743,11.748Z" fill="#36b37e"/>
                      </svg>
                    </span>
                  </span>
                </div>
              </article>

              <article className='flex flex-col px-4 py-4 bg-accent-3 rounded-lg'>
                <div className='relative flex flex-row items-center justify-items-center content-center justify-center w-60 h-32 rounded-lg bg-special'>
                  <div className='absolute top-4 right-4 w-9 h-9 rounded-full bg-white z-0'>
                      <div className='w-9 h-9 bg-accent-3 rounded-full flex items-center justify-items-center content-center justify-center'>
                        <svg xmlns="http://www.w3.org/2000/svg" width="10.4" height="13.365" viewBox="0 0 10.4 13.365">
                          <path id="Path" d="M2.8,0H7.6a2.8,2.8,0,0,1,2.8,2.8v9.365a1.2,1.2,0,0,1-1.969.921L5.456,10.6a.4.4,0,0,0-.512,0L1.969,13.086A1.2,1.2,0,0,1,0,12.165V2.8A2.8,2.8,0,0,1,2.8,0Z" fill="#5a7184"/>
                        </svg>
                      </div>
                  </div>
                </div>
                <div>
                  <h4 className='pt-5 pb-2 text-lg text-primary-text'>Brighten Up Dull Tired Skin</h4>
                  <p className='mb-4 text-sm'>Gravity is an irresistible force. While it is certainly nice that…</p>
                  <span className='flex flex-row items-center justify-items-center content-center justify-start gap-4'>
                    <span className='text-base text-secondary font-semibold'>Read More</span>
                    <span>
                      <svg xmlns="http://www.w3.org/2000/svg" width="12.251" height="11.941" viewBox="0 0 12.251 11.941">
                        <path id="arrow-right" d="M6.743,11.748l5.316-5.316a.654.654,0,0,0,0-.927L6.743.193a.654.654,0,0,0-.927,0L5.209.8a.652.652,0,0,0,.011.938L8.515,4.877H.656A.655.655,0,0,0,0,5.533v.875a.655.655,0,0,0,.656.656H8.515L5.22,10.2a.657.657,0,0,0-.011.938l.607.607A.654.654,0,0,0,6.743,11.748Z" fill="#36b37e"/>
                      </svg>
                    </span>
                  </span>
                </div>
              </article>

              <article className='flex flex-col px-4 py-4 bg-accent-3 rounded-lg'>
                <div className='relative flex flex-row items-center justify-items-center content-center justify-center w-60 h-32 rounded-lg bg-special'>
                  <div className='absolute top-4 right-4 w-9 h-9 rounded-full bg-white z-0'>
                      <div className='w-9 h-9 bg-accent-3 rounded-full flex items-center justify-items-center content-center justify-center'>
                        <svg xmlns="http://www.w3.org/2000/svg" width="10.4" height="13.365" viewBox="0 0 10.4 13.365">
                          <path id="Path" d="M2.8,0H7.6a2.8,2.8,0,0,1,2.8,2.8v9.365a1.2,1.2,0,0,1-1.969.921L5.456,10.6a.4.4,0,0,0-.512,0L1.969,13.086A1.2,1.2,0,0,1,0,12.165V2.8A2.8,2.8,0,0,1,2.8,0Z" fill="#5a7184"/>
                        </svg>
                      </div>
                  </div>
                </div>
                <div>
                  <h4 className='pt-5 pb-2 text-lg text-primary-text'>Brighten Up Dull Tired Skin</h4>
                  <p className='mb-4 text-sm'>Gravity is an irresistible force. While it is certainly nice that…</p>
                  <span className='flex flex-row items-center justify-items-center content-center justify-start gap-4'>
                    <span className='text-base text-secondary font-semibold'>Read More</span>
                    <span>
                      <svg xmlns="http://www.w3.org/2000/svg" width="12.251" height="11.941" viewBox="0 0 12.251 11.941">
                        <path id="arrow-right" d="M6.743,11.748l5.316-5.316a.654.654,0,0,0,0-.927L6.743.193a.654.654,0,0,0-.927,0L5.209.8a.652.652,0,0,0,.011.938L8.515,4.877H.656A.655.655,0,0,0,0,5.533v.875a.655.655,0,0,0,.656.656H8.515L5.22,10.2a.657.657,0,0,0-.011.938l.607.607A.654.654,0,0,0,6.743,11.748Z" fill="#36b37e"/>
                      </svg>
                    </span>
                  </span>
                </div>
              </article>
            </div>
          </section>

          {/* Promotions */}
          <section className='flex flex-col container mx-auto pt-10 px-5 bg-accent'>
            <h3 className='mb-5 text-lg text-center text-white font-bold'>Download ShopLive now and Get Promo Everyday</h3>
            <div className='flex flex-row px-5 pb-9 gap-4'>
              <button className='flex-auto rounded-lg bg-black'>&nbsp;</button>
              <button className='flex-auto rounded-lg bg-black'>&nbsp;</button>
            </div>
            <div className='h-48 rounded-t-lg bg-white'>&nbsp;</div>
          </section>
        </main>

        <footer className='bg-white container mx-auto flex flex-col flex-wrap gap-x-2 items-center justify-items-center content-center px-5 py-5'>
          <div className='flex flex-col flex-wrap gap-x-2 items-center justify-items-center content-center pb-14 order-last'>
            <h2 className="font-bold text-2xl flex-auto items-center flex flex-col justify-items-center content-center">
                <a href="/" className="flex flex-row flex-wrap gap-x-2 items-center text-accent">
                    <img src="/assets/img/footer_logo.svg" alt="Shoplive" />
                    <span className='hidden'>ShopLive</span>
                </a>
            </h2>
            <p className='text-center text-sm text-muted py-6'>Build a modern and creative website with Moonheads Digital</p>
            <section className='flex flex-row'>
              <div className='flex flex-col items-center justify-items-center content-center w-10 h-10 rounded-full bg-muted'>g</div>
              <div className='flex flex-col items-center justify-items-center content-center w-10 h-10 rounded-full bg-muted'>tw</div>
              <div className='flex flex-col items-center justify-items-center content-center w-10 h-10 rounded-full bg-muted'>ig</div>
              <div className='flex flex-col items-center justify-items-center content-center w-10 h-10 rounded-full bg-muted'>ln</div>
            </section>
          </div>
          <div className='grid grid-cols-2 gap-8 py-12 text-primary-text text-left'>
            <div>
              <h3 className='text-base'>Product</h3>
              <ul className='text-sm'>
                <li className='py-1'><a href='#'>Landing Page</a></li>
                <li className='py-1'><a href='#'>Features</a></li>
                <li className='py-1'><a href='#'>Documentation</a></li>
                <li className='py-1'><a href='#'>Referral Program</a></li>
                <li className='py-1'><a href='#'>Pricing</a></li>
              </ul>
            </div>
            <div>
              <h3>Services</h3>
              <ul className='text-sm'>
                <li className='py-1'><a href='#'>Documentation</a></li>
                <li className='py-1'><a href='#'>Design</a></li>
                <li className='py-1'><a href='#'>Themes</a></li>
                <li className='py-1'><a href='#'>Illustrations</a></li>
                <li className='py-1'><a href='#'>UI Kit</a></li>
              </ul>
            </div>
            <div>
              <h3>Company</h3>
              <ul className='text-sm'>
                <li className='py-1'><a href='#'>About</a></li>
                <li className='py-1'><a href='#'>Terms</a></li>
                <li className='py-1'><a href='#'>Privacy Policy</a></li>
                <li className='py-1'><a href='#'>Careers</a></li>
              </ul>
            </div>
            <div>
              <h3>More</h3>
              <ul className='text-sm'>
                <li className='py-1'><a href='#'>Documentation</a></li>
                <li className='py-1'><a href='#'>License</a></li>
                <li className='py-1'><a href='#'>Change Log</a></li>
              </ul>
            </div>
          </div>
        </footer>
      </div>
      
    </div>
  )
}

// export async function getStaticProps() {
//   const products = await getAllProducts()

//   return {
//     props: { products }, // will be passed to the page component as props
//   }
// }