import Head from 'next/head'
import Image from 'next/image'
import { getAllProducts } from '../utils/shopify'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  )
}

// export async function getStaticProps() {
//   const products = await getAllProducts()

//   return {
//     props: { products }, // will be passed to the page component as props
//   }
// }